global:
    resolve_timeout: 1m

route:
    receiver: 'gmail'
    repeat_interval: 1m

receivers:
    - name: 'gmail'
      email_configs:
          - to: shanumodi9@gmail.com
            from: shanumodi9@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: shanumodi9@gmail.com
            auth_identity: shanumodi9@gmail.com
            auth_password: npngdcmmiopspktn
            send_resolved: true
      slack_configs:
          - api_url: 'https://hooks.slack.com/services/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'
            channel: '#test123'
            send_resolved: true
